import Foundation

public struct WTHostSetupAssetGeometry: Hashable, Sendable {
    public let screen: String
    public let family: String
    public let canvas: WTSize
    public let glyphBounds: WTRect
    public init(screen: String, family: String, canvas: WTSize, glyphBounds: WTRect) {
        self.screen = screen; self.family = family; self.canvas = canvas; self.glyphBounds = glyphBounds
    }
}

public enum WTHostSetupGeometry353 {
    public static let all: [String: WTHostSetupAssetGeometry] = [
        "SetupAuxiliaryInput/blur_pinyin_left_dark": .init(screen: "SetupAuxiliaryInput", family: "blur_pinyin_left_dark", canvas: .init(width: 136.0, height: 56.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 136.0, height: 56.0)),
        "SetupAuxiliaryInput/blur_pinyin_left_light": .init(screen: "SetupAuxiliaryInput", family: "blur_pinyin_left_light", canvas: .init(width: 136.0, height: 56.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 136.0, height: 56.0)),
        "SetupAuxiliaryInput/blur_pinyin_right_dark": .init(screen: "SetupAuxiliaryInput", family: "blur_pinyin_right_dark", canvas: .init(width: 136.0, height: 56.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 136.0, height: 56.0)),
        "SetupAuxiliaryInput/blur_pinyin_right_light": .init(screen: "SetupAuxiliaryInput", family: "blur_pinyin_right_light", canvas: .init(width: 136.0, height: 56.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 136.0, height: 56.0)),
        "SetupAuxiliaryInput/icon_etc_dark": .init(screen: "SetupAuxiliaryInput", family: "icon_etc_dark", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 3.0, y: 5.0, width: 10.0, height: 6.0)),
        "SetupAuxiliaryInput/icon_etc_light": .init(screen: "SetupAuxiliaryInput", family: "icon_etc_light", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 3.0, y: 5.0, width: 10.0, height: 6.0)),
        "SetupClipboard/icon_table_arrow": .init(screen: "SetupClipboard", family: "icon_table_arrow", canvas: .init(width: 12.0, height: 20.0), glyphBounds: .init(x: 4.333, y: 4.333, width: 6.667, height: 12.0)),
        "SetupClipboard/img_clipboard_dark": .init(screen: "SetupClipboard", family: "img_clipboard_dark", canvas: .init(width: 295.0, height: 126.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 295.0, height: 126.0)),
        "SetupClipboard/img_clipboard_light": .init(screen: "SetupClipboard", family: "img_clipboard_light", canvas: .init(width: 295.0, height: 126.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 295.0, height: 126.0)),
        "SetupDesktop/icon_computer": .init(screen: "SetupDesktop", family: "icon_computer", canvas: .init(width: 160.0, height: 122.0), glyphBounds: .init(x: 1.0, y: 0.0, width: 158.0, height: 122.0)),
        "SetupDesktop/icon_computer_dark": .init(screen: "SetupDesktop", family: "icon_computer_dark", canvas: .init(width: 160.0, height: 122.0), glyphBounds: .init(x: 1.0, y: 0.0, width: 158.0, height: 122.0)),
        "SetupDesktop/icon_ios": .init(screen: "SetupDesktop", family: "icon_ios", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 7.333, y: 4.0, width: 17.667, height: 21.667)),
        "SetupDesktop/icon_windows": .init(screen: "SetupDesktop", family: "icon_windows", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.667, y: 6.667, width: 18.667, height: 18.667)),
        "SetupDisplaySetting/icon_font_big": .init(screen: "SetupDisplaySetting", family: "icon_font_big", canvas: .init(width: 17.0, height: 17.0), glyphBounds: .init(x: 2.667, y: 1.667, width: 11.667, height: 13.667)),
        "SetupDisplaySetting/icon_font_small": .init(screen: "SetupDisplaySetting", family: "icon_font_small", canvas: .init(width: 17.0, height: 17.0), glyphBounds: .init(x: 2.333, y: 2.667, width: 10.333, height: 11.667)),
        "SetupDisplaySetting/img_black_drak": .init(screen: "SetupDisplaySetting", family: "img_black_drak", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_black_light": .init(screen: "SetupDisplaySetting", family: "img_black_light", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_black_t9_dark": .init(screen: "SetupDisplaySetting", family: "img_black_t9_dark", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_black_t9_light": .init(screen: "SetupDisplaySetting", family: "img_black_t9_light", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_keyboard_height": .init(screen: "SetupDisplaySetting", family: "img_keyboard_height", canvas: .init(width: 299.0, height: 128.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 299.0, height: 128.0)),
        "SetupDisplaySetting/img_keyboard_height_dark": .init(screen: "SetupDisplaySetting", family: "img_keyboard_height_dark", canvas: .init(width: 299.0, height: 128.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 299.0, height: 128.0)),
        "SetupDisplaySetting/img_number_26": .init(screen: "SetupDisplaySetting", family: "img_number_26", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_number_26_dark": .init(screen: "SetupDisplaySetting", family: "img_number_26_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_number_9": .init(screen: "SetupDisplaySetting", family: "img_number_9", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_number_9_dark": .init(screen: "SetupDisplaySetting", family: "img_number_9_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_participle": .init(screen: "SetupDisplaySetting", family: "img_participle", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_participle_dark": .init(screen: "SetupDisplaySetting", family: "img_participle_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_sidebar_number": .init(screen: "SetupDisplaySetting", family: "img_sidebar_number", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_sidebar_number_dark": .init(screen: "SetupDisplaySetting", family: "img_sidebar_number_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_sidebar_pinyin": .init(screen: "SetupDisplaySetting", family: "img_sidebar_pinyin", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_sidebar_pinyin_dark": .init(screen: "SetupDisplaySetting", family: "img_sidebar_pinyin_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_system_dark": .init(screen: "SetupDisplaySetting", family: "img_system_dark", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_system_light": .init(screen: "SetupDisplaySetting", family: "img_system_light", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_system_t9_dark": .init(screen: "SetupDisplaySetting", family: "img_system_t9_dark", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_system_t9_light": .init(screen: "SetupDisplaySetting", family: "img_system_t9_light", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_t9_height_dark": .init(screen: "SetupDisplaySetting", family: "img_t9_height_dark", canvas: .init(width: 299.0, height: 128.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 299.0, height: 128.0)),
        "SetupDisplaySetting/img_t9_height_light": .init(screen: "SetupDisplaySetting", family: "img_t9_height_light", canvas: .init(width: 299.0, height: 128.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 299.0, height: 128.0)),
        "SetupDisplaySetting/img_uppercase": .init(screen: "SetupDisplaySetting", family: "img_uppercase", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_uppercase_dark": .init(screen: "SetupDisplaySetting", family: "img_uppercase_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/img_white_dark": .init(screen: "SetupDisplaySetting", family: "img_white_dark", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_white_light": .init(screen: "SetupDisplaySetting", family: "img_white_light", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_white_t9_dark": .init(screen: "SetupDisplaySetting", family: "img_white_t9_dark", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/img_white_t9_light": .init(screen: "SetupDisplaySetting", family: "img_white_t9_light", canvas: .init(width: 89.0, height: 50.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 89.0, height: 50.0)),
        "SetupDisplaySetting/pinyin_display_lower": .init(screen: "SetupDisplaySetting", family: "pinyin_display_lower", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/pinyin_display_lower_dark": .init(screen: "SetupDisplaySetting", family: "pinyin_display_lower_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/pinyin_display_upper": .init(screen: "SetupDisplaySetting", family: "pinyin_display_upper", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupDisplaySetting/pinyin_display_upper_dark": .init(screen: "SetupDisplaySetting", family: "pinyin_display_upper_dark", canvas: .init(width: 142.0, height: 80.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 142.0, height: 80.0)),
        "SetupFuzzyPinyin/icon_etc_dark": .init(screen: "SetupFuzzyPinyin", family: "icon_etc_dark", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 3.0, y: 5.0, width: 10.0, height: 6.0)),
        "SetupFuzzyPinyin/icon_etc_light": .init(screen: "SetupFuzzyPinyin", family: "icon_etc_light", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 3.0, y: 5.0, width: 10.0, height: 6.0)),
        "SetupKeyboardSelect/icon_add_dark": .init(screen: "SetupKeyboardSelect", family: "icon_add_dark", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 16.0, height: 16.0)),
        "SetupKeyboardSelect/icon_add_light": .init(screen: "SetupKeyboardSelect", family: "icon_add_light", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 16.0, height: 16.0)),
        "SetupKeyboardSelect/icon_delete_dark": .init(screen: "SetupKeyboardSelect", family: "icon_delete_dark", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 16.0, height: 16.0)),
        "SetupKeyboardSelect/icon_delete_light": .init(screen: "SetupKeyboardSelect", family: "icon_delete_light", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 16.0, height: 16.0)),
        "SetupKeyboardSelect/icon_table_arrow": .init(screen: "SetupKeyboardSelect", family: "icon_table_arrow", canvas: .init(width: 12.0, height: 20.0), glyphBounds: .init(x: 4.333, y: 4.333, width: 6.667, height: 12.0)),
        "SetupKeystrokeEffect/icon_voice_big": .init(screen: "SetupKeystrokeEffect", family: "icon_voice_big", canvas: .init(width: 17.0, height: 17.333), glyphBounds: .init(x: 0.667, y: 2.667, width: 15.667, height: 12.667)),
        "SetupKeystrokeEffect/icon_voice_small": .init(screen: "SetupKeystrokeEffect", family: "icon_voice_small", canvas: .init(width: 17.0, height: 17.333), glyphBounds: .init(x: 2.667, y: 3.0, width: 7.333, height: 12.0)),
        "SetupMain/icon_app_setup_about": .init(screen: "SetupMain", family: "icon_app_setup_about", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 5.333, y: 5.333, width: 21.333, height: 21.333)),
        "SetupMain/icon_app_setup_air": .init(screen: "SetupMain", family: "icon_app_setup_air", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 5.0, y: 4.0, width: 24.333, height: 23.333)),
        "SetupMain/icon_app_setup_computer": .init(screen: "SetupMain", family: "icon_app_setup_computer", canvas: .init(width: 32.333, height: 32.0), glyphBounds: .init(x: 5.0, y: 6.333, width: 22.0, height: 21.0)),
        "SetupMain/icon_app_setup_customize_toolbar": .init(screen: "SetupMain", family: "icon_app_setup_customize_toolbar", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 4.667, y: 5.667, width: 22.667, height: 20.667)),
        "SetupMain/icon_app_setup_help": .init(screen: "SetupMain", family: "icon_app_setup_help", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 5.333, y: 5.333, width: 21.333, height: 21.333)),
        "SetupMain/icon_app_setup_keyboard": .init(screen: "SetupMain", family: "icon_app_setup_keyboard", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 4.333, y: 5.333, width: 23.333, height: 21.667)),
        "SetupMain/icon_app_setup_multiple_devices": .init(screen: "SetupMain", family: "icon_app_setup_multiple_devices", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 4.333, y: 6.0, width: 23.333, height: 20.667)),
        "SetupMain/icon_app_setup_pluslogo": .init(screen: "SetupMain", family: "icon_app_setup_pluslogo", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 4.333, y: 4.333, width: 23.333, height: 23.333)),
        "SetupMain/icon_app_setup_privacy": .init(screen: "SetupMain", family: "icon_app_setup_privacy", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.333, y: 4.333, width: 19.333, height: 22.667)),
        "SetupMain/icon_app_setup_vibration": .init(screen: "SetupMain", family: "icon_app_setup_vibration", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 3.667, y: 7.0, width: 24.667, height: 17.667)),
        "SetupMain/icon_app_setup_voice": .init(screen: "SetupMain", family: "icon_app_setup_voice", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.333, y: 5.333, width: 20.333, height: 21.667)),
        "SetupMain/icon_app_title_large": .init(screen: "SetupMain", family: "icon_app_title_large", canvas: .init(width: 111.0, height: 21.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 110.333, height: 20.667)),
        "SetupMain/icon_arrow": .init(screen: "SetupMain", family: "icon_arrow", canvas: .init(width: 8.0, height: 12.0), glyphBounds: .init(x: 1.0, y: 0.667, width: 6.333, height: 10.667)),
        "SetupMain/icon_button_finish": .init(screen: "SetupMain", family: "icon_button_finish", canvas: .init(width: 16.0, height: 16.0), glyphBounds: .init(x: 2.333, y: 3.333, width: 12.333, height: 8.667)),
        "SetupMain/icon_clipboard": .init(screen: "SetupMain", family: "icon_clipboard", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 7.0, y: 5.0, width: 18.0, height: 21.0)),
        "SetupMain/icon_globe": .init(screen: "SetupMain", family: "icon_globe", canvas: .init(width: 24.0, height: 24.0), glyphBounds: .init(x: 2.0, y: 2.0, width: 20.0, height: 20.0)),
        "SetupMain/icon_home_askai": .init(screen: "SetupMain", family: "icon_home_askai", canvas: .init(width: 37.0, height: 24.0), glyphBounds: .init(x: 0.667, y: 3.667, width: 35.333, height: 16.667)),
        "SetupMain/icon_homepage_logo": .init(screen: "SetupMain", family: "icon_homepage_logo", canvas: .init(width: 60.0, height: 60.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 60.0, height: 60.0)),
        "SetupMain/icon_keybar_close": .init(screen: "SetupMain", family: "icon_keybar_close", canvas: .init(width: 24.0, height: 24.0), glyphBounds: .init(x: 7.0, y: 7.0, width: 10.0, height: 10.0)),
        "SetupMain/icon_layout": .init(screen: "SetupMain", family: "icon_layout", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 4.333, y: 5.333, width: 23.0, height: 21.0)),
        "SetupMain/icon_migration": .init(screen: "SetupMain", family: "icon_migration", canvas: .init(width: 20.0, height: 20.0), glyphBounds: .init(x: 4.0, y: 2.667, width: 12.0, height: 14.667)),
        "SetupMain/icon_setup_migration": .init(screen: "SetupMain", family: "icon_setup_migration", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.333, y: 4.667, width: 19.333, height: 22.667)),
        "SetupMain/icon_stars": .init(screen: "SetupMain", family: "icon_stars", canvas: .init(width: 24.0, height: 24.0), glyphBounds: .init(x: 0.0, y: 0.667, width: 24.0, height: 22.667)),
        "SetupMain/icon_table_arrow": .init(screen: "SetupMain", family: "icon_table_arrow", canvas: .init(width: 10.0, height: 16.667), glyphBounds: .init(x: 3.333, y: 3.667, width: 6.333, height: 10.0)),
        "SetupMigrationAssistant/icon_scan": .init(screen: "SetupMigrationAssistant", family: "icon_scan", canvas: .init(width: 26.0, height: 26.0), glyphBounds: .init(x: 5.0, y: 5.0, width: 16.0, height: 16.0)),
        "SetupMigrationAssistant/icon_tips_loading": .init(screen: "SetupMigrationAssistant", family: "icon_tips_loading", canvas: .init(width: 42.0, height: 42.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 42.0, height: 42.0)),
        "SetupMigrationAssistant/icon_tips_loading_dark": .init(screen: "SetupMigrationAssistant", family: "icon_tips_loading_dark", canvas: .init(width: 42.0, height: 42.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 42.0, height: 42.0)),
        "SetupMigrationAssistant/icon_update": .init(screen: "SetupMigrationAssistant", family: "icon_update", canvas: .init(width: 14.333, height: 14.0), glyphBounds: .init(x: 1.667, y: 1.0, width: 12.0, height: 12.333)),
        "SetupPlus/icon_app_kaomoji": .init(screen: "SetupPlus", family: "icon_app_kaomoji", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.667, y: 9.333, width: 18.333, height: 16.0)),
        "SetupPlus/icon_app_pinxieplus_ci": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_ci", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.667, y: 7.0, width: 18.333, height: 18.667)),
        "SetupPlus/icon_app_pinxieplus_correction": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_correction", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 9.333, y: 5.0, width: 16.0, height: 22.333)),
        "SetupPlus/icon_app_pinxieplus_emoji": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_emoji", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 5.667, y: 6.667, width: 20.333, height: 18.333)),
        "SetupPlus/icon_app_pinxieplus_logo": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_logo", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 32.0, height: 32.0)),
        "SetupPlus/icon_app_pinxieplus_quicksend": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_quicksend", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 7.667, y: 6.333, width: 17.333, height: 20.0)),
        "SetupPlus/icon_app_pinxieplus_smallemoji": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_smallemoji", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 5.0, y: 5.0, width: 22.0, height: 22.0)),
        "SetupPlus/icon_app_pinxieplus_textimage": .init(screen: "SetupPlus", family: "icon_app_pinxieplus_textimage", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.333, y: 6.0, width: 20.667, height: 19.333)),
        "SetupPlus/icon_app_retouching": .init(screen: "SetupPlus", family: "icon_app_retouching", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.333, y: 5.333, width: 19.667, height: 21.667)),
        "SetupPlus/icon_cell_info": .init(screen: "SetupPlus", family: "icon_cell_info", canvas: .init(width: 12.0, height: 12.0), glyphBounds: .init(x: 0.333, y: 0.333, width: 11.333, height: 11.333)),
        "SetupPlus/icon_pinxieplus_textpolish": .init(screen: "SetupPlus", family: "icon_pinxieplus_textpolish", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 5.333, y: 4.667, width: 21.667, height: 21.333)),
        "SetupPlus/icon_setup_ai": .init(screen: "SetupPlus", family: "icon_setup_ai", canvas: .init(width: 32.0, height: 32.0), glyphBounds: .init(x: 6.0, y: 7.0, width: 19.667, height: 17.667)),
        "SetupSp/icon_arrow": .init(screen: "SetupSp", family: "icon_arrow", canvas: .init(width: 24.0, height: 24.0), glyphBounds: .init(x: 7.667, y: 4.333, width: 8.667, height: 15.333)),
        "SetupSp/icon_sp_pyjj_dark": .init(screen: "SetupSp", family: "icon_sp_pyjj_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_pyjj_light": .init(screen: "SetupSp", family: "icon_sp_pyjj_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_sg_dark": .init(screen: "SetupSp", family: "icon_sp_sg_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_sg_light": .init(screen: "SetupSp", family: "icon_sp_sg_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_wr_dark": .init(screen: "SetupSp", family: "icon_sp_wr_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_wr_light": .init(screen: "SetupSp", family: "icon_sp_wr_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_xh_dark": .init(screen: "SetupSp", family: "icon_sp_xh_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_xh_light": .init(screen: "SetupSp", family: "icon_sp_xh_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_zg_dark": .init(screen: "SetupSp", family: "icon_sp_zg_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_zg_light": .init(screen: "SetupSp", family: "icon_sp_zg_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_znabc_dark": .init(screen: "SetupSp", family: "icon_sp_znabc_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_znabc_light": .init(screen: "SetupSp", family: "icon_sp_znabc_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_zrm_dark": .init(screen: "SetupSp", family: "icon_sp_zrm_dark", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_sp_zrm_light": .init(screen: "SetupSp", family: "icon_sp_zrm_light", canvas: .init(width: 3540.0, height: 1530.0), glyphBounds: .init(x: 0.0, y: 0.0, width: 3540.0, height: 1530.0)),
        "SetupSp/icon_table_select": .init(screen: "SetupSp", family: "icon_table_select", canvas: .init(width: 22.0, height: 22.0), glyphBounds: .init(x: 3.333, y: 5.333, width: 16.0, height: 12.0)),
        "SetupWb/icon_arrow": .init(screen: "SetupWb", family: "icon_arrow", canvas: .init(width: 24.0, height: 24.0), glyphBounds: .init(x: 7.667, y: 4.333, width: 8.667, height: 15.333)),
        "SetupWb/icon_table_select": .init(screen: "SetupWb", family: "icon_table_select", canvas: .init(width: 22.0, height: 22.0), glyphBounds: .init(x: 3.333, y: 5.333, width: 16.0, height: 12.0)),
    ]
    public static func geometry(screen: String, family: String) -> WTHostSetupAssetGeometry? { all["\(screen)/\(family)"] }
    public static var screens: [String] { Array(Set(all.values.map(\.screen)).sorted()) }
}
